name: Android Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      
    - name: Setup .NET
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 7.0.x
        
    - name: Install MAUI Workload
      run: dotnet workload install maui android
      
    - name: Restore dependencies
      run: dotnet restore "HojozatyCode - Copy/HojozatyCode/HojozatyCode.csproj"
      
    - name: Build Android App (Debug)
      run: dotnet build "HojozatyCode - Copy/HojozatyCode/HojozatyCode.csproj" -c Debug -f net7.0-android
      
    # Store build output using GitHub's artifact storage directly
    - name: Archive APK files
      uses: actions/upload-artifact@master
      with:
        name: android-apk-files
        path: |
          "HojozatyCode - Copy/HojozatyCode/bin/Debug/net7.0-android/**/*.apk"
