name: Android CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.cs'
      - '**.xaml'
      - '**.csproj'
      - '**.sln'
      - '**Props'
      - '**/Android/**'
      - '.github/workflows/android-cicd.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 7.0.x
        
    - name: Setup JDK
      uses: actions/setup-java@v2.5.0
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui android
      
    - name: Restore dependencies
      run: dotnet restore HojozatyCode/HojozatyCode.csproj
      
    - name: Build Android App (Debug)
      run: dotnet build HojozatyCode/HojozatyCode.csproj -c Debug -f net7.0-android
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v1.0.0
      with:
        name: hojozaty-debug-apk
        path: HojozatyCode/bin/Debug/net7.0-android/*.apk
        
    - name: Build Android App (Release)
      run: dotnet build HojozatyCode/HojozatyCode.csproj -c Release -f net7.0-android
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v1.0.0
      with:
        name: hojozaty-release-apk
        path: HojozatyCode/bin/Release/net7.0-android/*.apk
        
    # Optional: Sign APK for release distribution
    - name: Sign APK
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.base64
        certutil -decode keystore.base64 hojozaty.keystore
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore hojozaty.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -keypass "${{ secrets.KEY_PASSWORD }}" HojozatyCode/bin/Release/net7.0-android/com.hojozaty.app-Signed.apk "${{ secrets.KEY_ALIAS }}"
      shell: cmd
      continue-on-error: true
        
    - name: Upload Signed APK
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main') && success()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: hojozaty-signed-apk
        path: HojozatyCode/bin/Release/net7.0-android/*-Signed.apk
