name: Android CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui android
      
    - name: Restore dependencies
      run: dotnet restore HojozatyCode/HojozatyCode.csproj
      
    - name: Build Android App (Debug)
      run: dotnet build HojozatyCode/HojozatyCode.csproj -c Debug -f net7.0-android
      
    # Using GitHub's built-in artifact storage without an action
    - name: Archive Debug APK
      uses: actions/upload-artifact@v1
      with:
        name: hojozaty-debug-apk
        path: HojozatyCode/bin/Debug/net7.0-android/*.apk
        
    - name: Build Android App (Release)
      run: dotnet build HojozatyCode/HojozatyCode.csproj -c Release -f net7.0-android
      
    - name: Archive Release APK
      uses: actions/upload-artifact@v1
      with:
        name: hojozaty-release-apk
        path: HojozatyCode/bin/Release/net7.0-android/*.apk
